"""create offerimage table

Revision ID: 22fcb3fd5983
Revises: 845c7011feca
Create Date: 2026-09-11 10:21:10.554307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fcb3fd5983'
down_revision: Union[str, Sequence[str], None] = '845c7011feca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['Offer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_Offer_name'), table_name='Offer')
    op.create_index(op.f('ix_Offer_name'), 'Offer', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Offer_name'), table_name='Offer')
    op.create_index(op.f('ix_Offer_name'), 'Offer', ['name'], unique=False)
    op.drop_table('offer_image')
    # ### end Alembic commands ###
